sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --upload --pdf DMTR-182.pdf --lsstdoc DMTR-182.tex --env=travis --ltd-product dmtr-182"
env:
  global:
    - secure: "OBs6YIbYhIyCgideC+rfhKu1++JWxPJRj6h2AqcCnuoHF9dEyW3xcUYcyQ1ZURHT/XuA46niiuqmqiqTK4zf6iXpyhPPVWVO/RQ5i5W3vnKbQDvne9jp0b0bisI3rv4zQs6yoctBzetc5uibNfEGfiguhSm96tl6KVmHEg5Y5gVgja3OFTbds8bK+c8daiLqpYEJXzLqLMoWq1iCfnyfsOxY7Tja7HDcifV0pCxO6DjjJW97IqNgkGRFiB1mSI5R2FEiJx8hsQ+Yl7J2xzBTsPtsgbAGbL2+EfaU8RdR6UzBXSEdyqyNYsBiBaGpsijDYwS8agD1OUBstZ1g1Xu+V3riyozVOTBH+zbkVEU3nmeozOAX8wdAZVgo8WDQG2kAGldgRbLautj9yUrvNHmaxWJuG1AOEfg2mjwpaNKl9hocpstxCaGKkSy8YslQU30zVDzNNOCIy7YlYLRKw1gdL/SzXgsLc71IaLmLC+So8nOdW0gC99CtNQ1xPkGTiu9yAt6Nj4rtkIgf7a/SZk7xVPVlY+KZZ7FaHSXjYDQBnCPr6QiTlv0rIPiigamm8NCZ4DVzy+dP732+pXOpu7OEi1ZGA9BYZw329g8dvdupV/zBouT39nCbU+SLwWxD+6RMByGPWT+yVidpIp0KQKLdmIIPLQpU69Vdayd1qLIKaAk="
    - secure: "Jbj46fpprZnDf5oT+F9AnLauRMIdFWMuJ9iVa6DoN3zSR3rcDiAbUo2vsWYjv8jKQRe+bg86Lz5Brq00EDD9etzXtIRnhP1Y/P5kCkcMwK7BbS0klOerO3HyxX6wSgIax+84M7Ysh1xgURIHrGIPeffSwUkqqRxLBWp+zn/PIn+IdasjuX6QaFUyLnsqhPzOEmuznggy1YXMdhML1VF6y1ZzokyxUxgwy436lEZaWEq1vEt8BV3iMr8qaUvaEmiqmeGcBBl+9MnJZTTlD1n4zSkF9JxvWXqoRFTc6zMKGslxM0PjcZYEmKzYfWtCSDXU2gA/ZYAFkP3b/a3wQick3wBB3r/Fi5OSsLLzU8f3fYSryFpUZC/G8PcuuFeGfa3w149NwrPvSIYc8om5xP6gNlb5YPqM+hfoprqLIB4Y+DjnXa9KsXCIbZkZ7XnO1A7GELCSF+7OKCtgBLQZfmHQv5uKeDykOMR5ao6LSqv9sgoVUUM6Vcd/37Y7nGHteqjKQcW9FM5uDabE2TY4jfuKPnfQPYe2rjmVOBIGGT5paVHjFpfsNZMp9WAAU10VjISROCC/sNrTsK2A1efE1dPG1iDxTty6xGqTGaFR4pbB8mRD5rAZH1PSKbdBmjzcGrzEy17w5NGNOpm9PNCSz4hHU7kOql8vCSV7iQa8OZ9aG0o="
